Project Fixes & Additions
iwo-strzebonski/integra.content pull request #13
Opened 2023-09-20 09:51 UTC by Grallistrix

F10 - fixed desc in /projects/index
DuckieTown - added index desc+ created md
Hammerhead - updated index desc + created md
TWT - updated index desc + created md
Turbo - removed from index, does not exist

2023-09-24 09:30 UTC, eSqadron requested changes

2023-09-24 09:30 UTC, eSqadron commented on content/blog/projects/current/duckie-town.md
Paulina Iwulska przypadkiem nie opuściła koła?

2023-09-24 09:30 UTC, eSqadron commented on content/blog/projects/current/index.md
Nie trzeba zmodyfikować lastmoda w tym pliku też?

2023-09-25 19:15 UTC, Grallistrix commented on content/blog/projects/current/index.md
Już zmienione

2023-09-26 11:48 UTC, iwo-strzebonski commented on content/blog/projects/current/duckie-town.md
też mi się tak wydaje

2023-09-26 11:54 UTC, merged